//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddUserToPLUS
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public bool Administrator { get; set; }
        public string LoginID { get; set; }
        public byte[] Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public Nullable<System.DateTime> LastLoginDateTime { get; set; }
        public string Email { get; set; }
        public string ADobjectGUID { get; set; }
        public string ADuserPrincipalName { get; set; }
        public Nullable<bool> PromptResetPassword { get; set; }
        public bool Deactivated { get; set; }
        public Nullable<System.DateTime> DeactivatedDate { get; set; }
    }
}
